# Generated by Django 3.2.9 on 2021-11-21 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='owner_address',
            field=models.TextField(default=1),
        ),
    ]
